import type { Product, ProductId } from "@/entities/product"
import type { UpsertLocalProductPayload } from "@/features/local-products"

/**
 * Creates payload for creating a new local product
 * ID will be auto-generated by the store using nanoid
 *
 * @param productData - Product data without ID
 * @returns Payload for upsertLocalProduct action (create mode)
 */
export function createProductPayload(
  productData: Omit<Product, "id">
): UpsertLocalProductPayload {
  return {
    data: productData,
  }
}

/**
 * Creates payload for updating an existing product
 * Works for both local and API products
 *
 * @param productData - Product data without ID
 * @param id - Product ID to update (string-based)
 * @returns Payload for upsertLocalProduct action (update mode)
 */
export function updateProductPayload(
  productData: Omit<Product, "id">,
  id: ProductId
): UpsertLocalProductPayload {
  return {
    id,
    data: productData,
  }
}
